// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClsC0QDYxSj37QenJNbJeV8UhkktK64a8',
    appId: '1:858497408602:web:c71f3f02357f17ddb98263',
    messagingSenderId: '858497408602',
    projectId: 'questforkids-7e3dc',
    authDomain: 'questforkids-7e3dc.firebaseapp.com',
    storageBucket: 'questforkids-7e3dc.firebasestorage.app',
    measurementId: 'G-GMBCGH9EBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjFu26gpNSvq_Dk5USLSVcnWZjsZtDs6I',
    appId: '1:858497408602:android:c8c397d039f51cceb98263',
    messagingSenderId: '858497408602',
    projectId: 'questforkids-7e3dc',
    storageBucket: 'questforkids-7e3dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5vGltWfLThLbugiqUHPmnSxYsjw4zKT8',
    appId: '1:858497408602:ios:d040c38926ae3514b98263',
    messagingSenderId: '858497408602',
    projectId: 'questforkids-7e3dc',
    storageBucket: 'questforkids-7e3dc.firebasestorage.app',
    iosBundleId: 'com.example.questForKids',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5vGltWfLThLbugiqUHPmnSxYsjw4zKT8',
    appId: '1:858497408602:ios:d040c38926ae3514b98263',
    messagingSenderId: '858497408602',
    projectId: 'questforkids-7e3dc',
    storageBucket: 'questforkids-7e3dc.firebasestorage.app',
    iosBundleId: 'com.example.questForKids',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClsC0QDYxSj37QenJNbJeV8UhkktK64a8',
    appId: '1:858497408602:web:88cb485d7d619db5b98263',
    messagingSenderId: '858497408602',
    projectId: 'questforkids-7e3dc',
    authDomain: 'questforkids-7e3dc.firebaseapp.com',
    storageBucket: 'questforkids-7e3dc.firebasestorage.app',
    measurementId: 'G-7EV0WH0YTJ',
  );
}
