import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../domain/entities/reward_entity.dart';
import '../../domain/repositories/reward_repository.dart';
import '../../data/repositories/reward_repository_impl.dart';
import '../../../notifications/domain/entities/notification_entity.dart';
import '../../../notifications/presentation/providers/notification_providers.dart';

// --- Dependencies ---
final firestoreProvider = Provider((ref) => FirebaseFirestore.instance);

// --- Repository Provider ---
final rewardRepositoryProvider = Provider<RewardRepository>((ref) {
  return RewardRepositoryImpl(ref.watch(firestoreProvider));
});

// --- Controller ---
class RewardController extends AsyncNotifier<void> {
  @override
  Future<void> build() async {}

  Future<void> createReward({
    required String name,
    required int cost,
    String? imageUrl,
    required String parentId,
  }) async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      final reward = RewardEntity(
        id: '', // Generated by repo
        name: name,
        cost: cost,
        imageUrl: imageUrl,
        parentId: parentId,
      );
      await ref.read(rewardRepositoryProvider).createReward(reward);
    });
  }

  Future<void> updateReward({
    required String id,
    required String name,
    required int cost,
    String? imageUrl,
    required String parentId,
  }) async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      final reward = RewardEntity(
        id: id,
        name: name,
        cost: cost,
        imageUrl: imageUrl,
        parentId: parentId,
      );
      await ref.read(rewardRepositoryProvider).updateReward(reward);
    });
  }

  Future<void> deleteReward(String parentId, String rewardId) async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      await ref.read(rewardRepositoryProvider).deleteReward(parentId, rewardId);
    });
  }

  Future<void> redeemReward({
    required String parentId,
    required String childId,
    required String rewardId,
    required int cost,
  }) async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      await ref
          .read(rewardRepositoryProvider)
          .redeemReward(parentId, childId, rewardId, cost);

      // --- Send Parent Notification ---
      // We assume generic message for now.
      final notification = NotificationEntity(
        id: '', // Generated by Repo
        title: 'Reward Redeemed! 🎁',
        message: 'A reward has been redeemed! (- $cost KP)',
        timestamp: DateTime.now(),
        isRead: false,
        type: NotificationType.rewardRedeemed,
        childId: childId,
        relatedId: rewardId,
      );

      await ref
          .read(notificationRepositoryProvider)
          .sendNotification(parentId, notification);
    });
  }
}

final rewardControllerProvider = AsyncNotifierProvider<RewardController, void>(
  RewardController.new,
);

// --- Streams ---
final rewardsStreamProvider = StreamProvider.family<List<RewardEntity>, String>(
  (ref, parentId) {
    return ref.read(rewardRepositoryProvider).getRewards(parentId);
  },
);
